# Generated by Django 2.2.4 on 2019-08-03 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(max_length=100)),
                ('USER_PASS', models.CharField(max_length=100)),
                ('USER_NAME', models.TextField()),
                ('CREATE_DATE', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
