# Generated by Django 2.2.3 on 2019-10-01 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(max_length=100)),
                ('USER_TITLE', models.CharField(max_length=10)),
                ('USER_CONTENT', models.TextField(blank=True)),
                ('OP_DATE', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
