# Generated by Django 2.2.3 on 2019-10-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='USER_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
